### ISSUE TITLE
Removing body checks

### ISSUE THREAD

**Issue by tamirazrab** [ProMehedi/elysia-api-starter#1]
Hi, coming from nest-js background, I've seen this in couple of controllers, is there anyway to avoid it? Like I'm assuming that input is validated at route before it reaches into controller . 

```
  //   Check for body
  if (!c.body) throw new Error('No body provided')
```

Does below doesn't ensure that input is required?

```
 t.Object({
          name: t.String(),
          email: t.String(),
          password: t.String(),
          isAdmin: t.Optional(t.Boolean()),
        }),
```

One of-topic question, I saw couple of small things missing, like husky, good formatter maybe biome, are you accepting PR's to fill that void? I can contribute.

**Comment by ProMehedi** [comment]
Hi, Thanks for asking.

If I don't check for the body I will get errors. But that is an unknowing error. 
Like this one - 
![image](https://github.com/ProMehedi/elysia-api-starter/assets/21347335/d2e648f0-0f3e-4b76-bd35-9dc1de56f4e0)

Another issue is that If I don't check for the body I will get errors for the next line.
![image](https://github.com/ProMehedi/elysia-api-starter/assets/21347335/d57f37d5-322c-44eb-b8ad-fea263259bda)
![image](https://github.com/ProMehedi/elysia-api-starter/assets/21347335/db0565c1-3061-448d-a421-2d603c0b4629)

About missing things, I just started this repo I will update it as needed. And of course, I will be happy to have awesome contributions

**Comment by tamirazrab** [comment]
Thanks for detailed answer, I'll try to send some PR's soon.
